- src/Components/Modules/ZoneBuilder.cpp
- src/Components/Modules/Zones.cpp
AssetHandler::ModifyAsset checks the zone version and then applies a patch, this won't work with maps compiled with zonebuilder because the ff version is the same as other iw4 zones.  Therefore the sortkey needs to be fixed when the map gets built instead of at runtime.
> Update ZoneBuilder.cpp for building CoDOL Maps

- src/Steam/Steam.cpp
_Someone_ left a **y** where an **x** should be
> Fix typo in steam mod

- src/Components/Modules/ServerList.cpp
Sort ServerList by player count by default, I assume this is whats most useful.
Also referencing the following rawfiles PR this is the better solution in my opinion.
https://github.com/iw4x/iw4x-rawfiles/pull/3
> Sort ServerList by players

- src/Components/Modules/Auth.cpp
This PR extends the list of banned UIDs by one.
It forces the players using this shared ID to generate a new and unique one.
> Ban another guid that got shipped in a repack of the game.

- src/Components/Modules/Bots.cpp
- src/Components/Modules/Bots.hpp
- src/Components/Modules/GSC/IO.cpp
- src/Components/Modules/GSC/ScriptStorage.cpp
- src/Game/BothGames.cpp
- src/Game/BothGames.hpp
- src/Game/Script.hpp
My Bot Warfare mod (https://github.com/ineedbots/iw4_bot_warfare) will be compatible with this client with these changes. Bots will be able to press the Use button on objects, bots will be able to use alt weaponry properly. Added `botMeleeParams` builtin to allow bots to melee lung
Nothing is breaking.
Max SL string length is actually 65535, not 1023, this is a required change for Bot Warfare reading waypoints. "scriptdata/" is NOT added to filepath if it already exists in the argument.
> Compatibility and improvements for Bot Warfare

- src/Components/Modules/Auth.cpp
- src/Components/Modules/Logger.cpp
- src/Components/Modules/Logger.hpp
- src/Components/Modules/Network.cpp
- src/Components/Modules/Network.hpp
- src/Components/Modules/RCon.cpp
- src/Components/Modules/Security.cpp
- src/Components/Modules/Voice.cpp
Allows the user to harden their servers from unwanted attacks such as RCon password brute force.
This PR adds a few prints to critical sections of the code where I think a possible attacker may attempt to send invalid data.
- Adds a dvar that controls where the log file is written default: `/var/iw4x.log` (taken from fail2ban docs. For testing I used to change it to `userraw/logs/iw4x.log`. 
- Adds command line arg to set this feature one.
I used these fail2ban configs and I tested them well enough confirming they work out of the box https://git.alterware.dev/AlterWare/iw4x-fail2ban
Once this PR merged I encourage the creation of a similar repo or otherwise distribute the files under …
> Feat: Native integration with Fail2Ban for Linux server Hosters

- src/Components/Modules/Download.cpp
- src/Components/Modules/Download.hpp
Old feature by momo, his old code didn't work because he forgot to to call dump hex on the server password.
I removed it during the great refactoring of download.cpp when we upgraded past 4 major releases of mongoose.
Now I add it back
> fix(download): restore password verification

- src/Components/Modules/RCon.cpp
- src/Components/Modules/RCon.hpp
- Remove momo5502's funny code
- Add a return statement when RSA key (needed for safe RCon patch) is invalid
- Make the client not crash when an invalid RSA key is detected
- Make client better
No
> RCon: remove ECC & related functions + fix logic bug

- src/Components/Modules/Maps.cpp
Removing this hook fixes the crash when loading into Chinatown. 
Closes https://github.com/iw4x/iw4x-client/issues/72
I did not pick up on any unwanted changes.
It might be worth looking into the Chinatown to figure out what sets it apart from the rest. One thing I noted was that the loading screen for this map seems to struggle with showing the correct map name: it will start off with "Chinatown" briefly, then show "Unknown", and finally, "Chinatown" again. The console reports `Overriding asset 'MPUI_CARENTAN' of type localize`. This is the only map I noticed that would do this.
> fix: removed hook that can crash when loading zone

- src/Components/Modules/ServerList.cpp
PluTools recently renamed to getServe.rs, coming with a new domain.
While plutools.pw will be available for about another year, getserve.rs should be used.
> Replace plutools.pw with getserve.rs

- src/Components/Modules/Bots.cpp
- src/Game/Structs.hpp
Add `BotRemoteAngles` and `BotAngles` builtin methods for bots
Fixes `ads` `BotAction` not throwing (allows bots to shoot akimbo weapons)
Adds `remote` `BotAction`
`BotStop` assigns current weapon
Thanks for the contribution! Please provide a concise description of the problem this request solves.
Specify the new expected behaviour if this PR adds a new gameplay feature or alters an existing game mechanic. You may provide an image or video showing the changes.
> Add BotRemoteAngles and BotAngles

- src/Components/Modules/Vote.cpp
- src/Components/Modules/Vote.hpp
Adds the ```sv_votesrequired``` dvar which allows setting the amount of votes required for a voting (```g_allowvote```) to pass.
The default value of ```0``` will result in the value being calculated from player count (```players / 2 +1```).
The default votes required will deviate. Previously a fixed amount of votes was required, with this change a majority is required by default (```players / 2 +1```). It should behave the same as before by setting ```sv_votesrequired``` to 3.
> Add sv_votesrequired

- src/Components/Modules/MapRotation.cpp
With the newer configs random map dvar does not work. this fixes that
Makes the rotation randomized on request by the user with the new configs
No, this is a bug fix
> fix(map rotation): make random map dvar work again with new configs

- src/Components/Modules/RawMouse.cpp
- src/Components/Modules/RawMouse.hpp
This PR addresses a bug where the cursor could move outside the game window during a flick (a very quick mouse movement to reposition the crosshair). It should also prevent the mouse cursor from "jumping" to second monitor.
> Clip cursor to the game window.

- src/Components/Modules/Dvar.cpp
- src/Components/Modules/Dvar.hpp
- src/Components/Modules/Gamepad.cpp
- src/Components/Modules/Gamepad.hpp
This commit removes all references to it and uses `aim_lockon_strength` as the scale/strength factor when calculating the lock-on pitch turn rate. This aligns with the behavior in the Xbox 360 version of the game.
I am unsure as I do not have a controller to test.
The dvar `aim_lockon_pitch_strength` exists in T5 (I believe from recollection). Whether there should be seperate dvars for lock-on pitch and yaw strength is another question, and if so, the dvars should then be registered properly.
> Discard non-existent dvar

- src/Components/Modules/PlayerMovement.cpp
- src/Components/Modules/PlayerMovement.hpp
- src/Components/Modules/Weapon.cpp
- src/Components/Modules/Weapon.hpp
Addresses parts of #61 (do not close yet)
Breaking: change dvar name (necessary to avoid bad confusion as it did in the past: bg(both games) name will lead someone who is familiar with quake engine to think that dvar is checked by server side when it is NOT and must cheat protected because it is CG category (client game)
Yes: above there is an explanation
no
> fix dvar name in player movement

- src/Components/Modules/Download.cpp
- src/Components/Modules/ModList.cpp
- src/Components/Modules/ModList.hpp
- src/Components/Modules/Party.cpp
Closes #139 
Unloads the mod, if loaded, when leaving a server
Fixes some bugs I spotted(unterminated Cbuf strings) in the mod list code
As explained in the code #70 does not allow me to unload a mod when leaving a private match
> [Mods]: Clear fs_game when leaving servers

- .gitmodules
This allows cloning on machines that don't have an ssh key set up on github.
> Use https git url for dualsense-windows

- src/Components/Modules/RawMouse.cpp
- src/Components/Modules/RawMouse.hpp
- src/Game/Functions.cpp
- src/Game/Functions.hpp
- src/Game/Game.cpp
- src/Game/Game.hpp
- src/Game/Structs.hpp
- src/Game/System.cpp
- src/Game/System.hpp
This pull request fixes an fps drop caused by bottleneck of window messages when using high polling rate mouse (8k).
These changes includes RIDEV_NOLEGACY flag to RegisterRawInputDevices, disabling legacy WindowProc messages for input device we register.
I had to fix issues with mouse input when m_raw_input is 0, and also issues that are including with lack of legacy messages 
that i managed to fix with disabling raw input (handling WM_KILLFOCUS, WM_SETFOCUS, mouse going away from client screen space (WM_MOUSELEAVE)).
Since the legacy messages are gone, i made mouse input fully raw when using m_raw_input 1 (handling buttons, scroll).
here is the result (m_raw_input 0 will create fps drops since it uses game's old behaviour):
https://github.com/user-attachments/assets/40b69069-132b-409f-853 …
> Fix of fps drop when using a high polling rate mouse

- README.md
- src/Components/Modules/AssetInterfaces/ILocalizeEntry.cpp
Makes CoD4 str parsing exclusive to a flag. Undoing this default behaviour will make ZB modder friendly and can allow Louvenarde to undo the JSON localized string parsing from the IW4x rawfiles
No longer adds prefix to localized strings derived from .str file name (CoD4 mod tools behaviour)
No
> fix: make .str parsing with ZB useful

- src/Components/Modules/Gamepad.cpp
- src/Components/Modules/Gamepad.hpp
Fix performance issue from gamepad under specific scenario (e.g. running under wine). 
Note: under 10 fps will cause trigger roles to lock but this should be considered as a different issue.
> Fix gamepad performance

- src/Components/Modules/Dedicated.cpp
- src/Components/Modules/Party.cpp
Fixes #174 
~~Removes a command that executes a cfg that was entirely fabricated by the minds of the OG iw4x's devs and does not exist at all~~ (Reverted: see below) 
The dvar mess is now gone, the private match dvar is registered by the live_init function and our custom privateserver function is registered by us because we use it in the info handlers
> fix: restore lobby server / wider crashes

- src/Game/Structs.hpp
This improves the layout of the gentity_s struct.
None of the existing code should be affected. I cannot find any references to gentity fields below gentity_s::count, so there shouldn't be any offset problems.
This is based on iw4 xbox360 debug information. Some of the type and field names are my own as I couldn't find their actual names. The struct change should be helpful for the antilag pr:  https://github.com/iw4x/iw4x-client/pull/169#pullrequestreview-2479676404
> Improved gentity struct.

- deps/premake/zlib.lua
Wine leads Premake to incorrectly detect unistd.h as available because it exposes the host environment (e.g., /usr/include/) while emulating a Windows system. Since Wine designates the host system as Window, we can ensure that HAVE_UNISTD_H is only set when Premake is running natively (e.g., when generating MinGW Make config)
> Fix HAVE_UNISTD_H definition with MSBuild under Wine

- src/Components/Modules/Theatre.cpp
Replaces the `%s` format specifier, which is not recognized by `std::format`, with the appropriate `{}` placeholders.
I noticed that the demo metadata files (i.e., `.json`) are not being deleted whilst the demo files (i.e., `.dm_13) are.
This pull request should resolve the issue by ensuring that the metadata files residing alongside the demos are also automatically deleted based on `cl_demosKeep`.
> Use {} placeholders for std::format to resolve demo metadata files not being automatically deleted.

- src/Components/Modules/News.cpp
- src/Components/Modules/News.hpp
Polling every 3 minutes for MOTD update is wasteful, especially since content rarely changes. Instead, we can simplify implementation by fetching MOTD once during initialization and skipping periodic updates altogether.
This also removes the wine check that prevented changelog and MOTD from loading. Not sure why it was introduced, and blame doesn't reveal much about it:
> Skip MOTD periodic updates

- src/Components/Modules/MapRotation.cpp
Fixes issue where private matches would map_restart after every game. Players are returned to the lobby instead.
Applies to private matches only.
> fix: auto-restarting the same map in private match

- src/Components/Modules/QuickPatch.cpp
makes the iw4x intro skippable.
a lot of users set the intro dvar to 0 or use the -nointro flag as its unskippable, with this change it can be skipped by clicking once.
> make intro/IW_logo cinematic skippable

- src/Components/Modules/Party.cpp
- src/Components/Modules/Theatre.cpp
- src/Game/Common.cpp
- src/Game/Common.hpp
- src/Game/Database.hpp
- src/Game/Functions.cpp
Implements Private match functionality that was missing in IW4x - works like in the traditional game.
This reuses Party code and uses a new match type handler so **existing functionality is not affected**
This does not require a protocol change!
> Implement missing handler for Private party joining

- src/Components/Modules/RawMouse.cpp
- src/Components/Modules/RawMouse.hpp
When a gamepad is connected, GetRawInputData() may require more buffer space than the fixed sizeof(RAWINPUT) allocation provides.
Reference: https://github.com/iw4x/iw4x-client/pull/297
> Fix GetRawInputData buffer overflow with gamepad connections

- src/Components/Modules/Localization.cpp
- src/Components/Modules/Localization.hpp
- src/Components/Modules/Maps.cpp
- src/Components/Modules/Maps.hpp
- src/Game/Script.cpp
- src/Game/Script.hpp
Adds various GSC functions very useful to make a map voting menu, among other things
Adds scripting functions
Not sure if LocalizeText isn't already a thing, I think it isn't, pretty sure it isn't, but maybe someone will correct me on this
- [ X] Focus on a single fix or feature; remove any unrelated formatting or code changes
- [X ] Mention any [related issues](https://github.com/iw4x/iw4x-client/issues) (put `closes #XXXX` in comment to auto-close issue when PR is merged)
- [X ] Follow our [coding conventions](https://github.com/iw4x/iw4x-client/blob/master/CODESTYLE.md)
- [X ] Minimize the number of commits
> Mapvote GSC helpers
