iw4x/iw4x-client

README.md

update cli args

---

src/Components/Modules/Maps.cpp

fix COD:OL zm maps

---

src/Components/Loader.cpp
src/Components/Modules/QuickPatch.cpp
src/Components/Modules/Singleton.cpp
src/Components/Modules/Singleton.hpp
src/Components/Modules/Updater.cpp
src/Components/Modules/Updater.hpp
src/Game/System.cpp
src/Game/System.hpp
src/Utils/Library.cpp

- Auto updater
- Fixes singleton component memory leak

feature: auto updater!

---

src/Components/Modules/Auth.cpp

Extends Fail2Ban protection to cover for failed g_password connect attempts

feat: log failed g_password login/connect attempts

---

src/Components/Modules/FastFiles.cpp
src/Components/Modules/FastFiles.hpp
src/Components/Modules/FileSystem.cpp
src/Components/Modules/FileSystem.hpp
src/Components/Modules/ZoneBuilder.cpp
src/Game/FileSystem.cpp
src/Game/FileSystem.hpp
src/Game/Structs.hpp
src/Game/System.cpp
src/Game/System.hpp
src/Utils/Utils.cpp
src/Utils/Utils.hpp

Tested by me and xerxes, see discord of images of iw4x running in eggs

feat: containers!

---

src/Components/Modules/QuickPatch.cpp
src/Utils/Library.cpp
src/Utils/Library.hpp
src/Utils/Utils.cpp
src/Utils/Utils.hpp

fix command line arguments for alterware-launcher.exe

---

deps/premake/zlib.lua

c.f. https://github.com/iw4x/iw4-open-formats/pull/36

 Tests for unistd.h, and includes it if present

---

src/Components/Modules/PlayerMovement.cpp

Closes #147 Dvars that are server side do not need to be cheat protected because the server will correct any out of sync client

[PlayerMovement] Tackle some issues with Dvar flags

---

src/Components/Modules/Gamepad.cpp
src/Components/Modules/Gamepad.hpp

Refreshes gamepad on another thread and uses a mutex lock so the game can read from it

Fix performance issues waiting on controller IO at a very high framerate

---

src/Components/Modules/Dedicated.cpp
src/Components/Modules/Party.cpp

Revert "fix: restore lobby server / wider crashes"

---

src/Components/Modules/Dedicated.cpp
src/Components/Modules/Party.cpp

Fix issue #174
Specify the new expected behaviour if this PR adds a new gameplay feature or alters an existing game mechanic. You may provide an image or video showing the changes.

fix: Lobby Server/Other Crash

---

src/Components/Modules/Gamepad/Controller.cpp
src/Components/Modules/Rumble.cpp

Big fix for saving dvars
Specify the new expected behaviour if this PR adds a new gameplay feature or alters an existing game mechanic. You may provide an image or video showing the changes.

fix flags for  rumble dvars

---

src/Components/Modules/ZoneBuilder.cpp
src/Game/Functions.cpp
src/Game/Functions.hpp
src/Game/Game.cpp
src/Game/Game.hpp
src/Game/System.cpp
src/Game/System.hpp

Fixes #151 
None I suppose
Hopefully no

[ZB]: Update how cmd line is used

---

src/Components/Modules/FileSystem.cpp
src/Components/Modules/FileSystem.hpp
src/Components/Modules/Logger.cpp
src/Components/Modules/Logger.hpp
src/Game/Common.cpp
src/Game/Common.hpp
src/Game/FileSystem.cpp
src/Game/FileSystem.hpp
src/Game/Functions.cpp
src/Game/Functions.hpp
src/Utils/Utils.cpp
src/Utils/Utils.hpp

fix logfile creation with multiple instances

---

src/Components/Modules/ZoneBuilder.cpp

[chore] update zonebuilder help formatting

---

src/Components/Modules/ServerList.cpp
src/Utils/Cache.cpp

iw4x.getserve.rs -> iw4x.dev
this should be its final™ home

Update new domain

---

src/Components/Modules/MapRotation.cpp

Closes #268
Specify the new expected behaviour if this PR adds a new gameplay feature or alters an existing game mechanic. You may provide an image or video showing the changes.

Fix Lobby servers

---

.editorconfig
generate-linux.sh

Sets up (automate) required environment to build IW4x using Microsoft Visual C++ (MSVC) toolchain from a Linux host

Add script for building with MSVC on Linux

---

src/Components/Modules/Voice.cpp
src/Components/Modules/Voice.hpp

add sv_alltalk
https://github.com/iw4x/iw4x-client/issues/288

sv_alltalk

---

src/DllMain.cpp

According to the Windows DLL lifecycle contract, lpvReserved is non-null during implicit unload (i.e., process termination), and null when the DLL is being unloaded explicitly via FreeLibrary.
In the termination case, the process environment is in an unstable or partially deconstructed state. Calling into runtime or application logic during this phase is undefined behavior.
To prevent such, we want to only call when invoked via FreeLibrary, where the runtime remains valid.
Resolves #209

Avoid teardown during process termination in DllMain

---

src/Components/Modules/ServerList.cpp

This post allows the client to start using the master server again.
There should be no breaking changes in this PR. This will allow the client to contact a new master server to retrieve a server list. As of now, there is no back up master server. If the master does not respond for any reason, the client will still fall back to the node system. No gameplay changes.
None!

masters back ;)
